#!/usr/bin/perl

$Service=undef;
$find = "&quot;";
$find = quotemeta $find;
$monitorStatusFile="/usr/local/ffm/scripts/feeders/mappingNagios";
my $statusfileBackup='/usr/local/ffm/nagios/var/statusBackup.dat';
%status_hash = ();

$Service.="########################################
#          NAGIOS STATUS FILE
#
# THIS FILE IS AUTOMATICALLY GENERATED
# BY NAGIOS.  DO NOT MODIFY THIS FILE!
########################################

";
sub dbQuery(){
#$Service=undef;
$Service.="info {
        created=1413145549
        version=3.4.1
        last_update_check=0
        update_available=0
        last_version=
        new_version=
        }\n\n";

@data=`/usr/local/ffm/postgresql/bin/psql -U cpfadmin -d cpfdatamodeldb -c "select h.hostid, h.hostname ,ss.servicedescription, m.name as MonitorStatus,ssp.valuestring as LastPluinOutPut from host as h inner join servicestatus as ss on h.hostid=ss.hostid inner join monitorstatus as m on ss.monitorstatusid = m.monitorstatusid inner join servicestatusproperty as ssp on ssp.servicestatusid=ss.servicestatusid" >databaseFile;`;

#`awk '{print \$3,\$5,\$7,\$9,\$10,\$11,\$12}' databaseFile | sed 1d | head -n -2 |sed 1d> file.txt`;
`cat databaseFile | sed 1d | head -n -2 |sed 1d > file.txt`;

#`rm -rf databaseFile`;
}
sub makingFile(){
	open HANDLE, "file.txt" or die $!;
	my @array=<HANDLE>;
	chomp @array;
	close HANDLE;
	foreach (@array){
			$hostid=&trim(`echo "$_" | cut -d'|' -f1`);chomp $hostid;&trim($hostid);
			$name=&trim(`echo "$_" | cut -d'|' -f2`);chomp $name;&trim($name);
			$serviceDec=&trim(`echo "$_" | cut -d'|' -f3`);chomp $serviceDec;&trim($serviceDec);
			$monitorStatus=	&trim(`echo "$_" | cut -d'|' -f4`); chomp $monitorStatus;&trim($monitorStatus);
			$lastPluginOutput=&trim(`echo "$_" | cut -d'|' -f5 `);chomp $lastPluginOutput;&trim($lastPluginOutput);$lastPluginOutput =~ s/$find/\"/g ; 
			$Service.="servicestatus {\n\t"."host_name=$name\n\t"."host_id=$hostid\n\t"."service_description=$serviceDec\n\t"."current_state=$status_hash{$monitorStatus}\n\t"."plugin_output=$lastPluginOutput"."\n\t"."last_check=1415907986"."\n\t"."}\n\n";
	}

	$Service.="contactstatus {
        contact_name=nagiosadmin
        modified_attributes=0
        modified_host_attributes=0
        modified_service_attributes=0
        host_notification_period=
        service_notification_period=24x7
        last_host_notification=0
        last_service_notification=0
        host_notifications_enabled=1
        service_notifications_enabled=1
        }\n\n";
#`rm -rf file.txt`;	
}

sub creatingFile(){
	unlink("$statusfileBackup");	
	open FILEHANDLE, ">>$statusfileBackup" or die $!;
	
	print FILEHANDLE $Service;	
	close FILEHANDLE;
		
}

sub creatingHostStatus(){


	$Host="cat file.txt | awk '{print \$3}' | uniq";
	#$Host="cat file.txt | cut -d'|' -f2 | uniq";
	@hostStatus=`$Host`;
	foreach (@hostStatus){
		chomp $_;
		&trim($_);
		$Service.="hoststatus {\n\t"."host_name=$_"."\n\t"."has_been_checked=1"."\n\t"."last_check=1415907986"."\n\t"."}\n\n";
	}
}

sub MonitorstatusCheck(){
#	%status_hash = ();
# Read and build status hash
	open STATUS, "$monitorStatusFile";
	while (<STATUS>){
        	chomp;
       		 ($v, $k) = split(/;/);
	        $status_hash{$k} = $v;
	}

}

sub ltrim { my $s = shift; $s =~ s/^\s+//;       return $s };
sub rtrim { my $s = shift; $s =~ s/\s+$//;       return $s };
sub  trim { my $s = shift; $s =~ s/^\s+|\s+$//g; return $s };

sub mainFunction(){
`rm -rf $statusfileBackup`;
&dbQuery;
&MonitorstatusCheck;
&creatingHostStatus;
&makingFile;
&creatingFile;
$Service=undef;
}
#&mainFunction;
#$Service=undef;
